---
title: "false-color-images"
format: html
---

```{r}
library(tidyverse)
library(sf)
library(terra)
library(tmap)
library(tmaptools)
library(RColorBrewer)
```

```{r}
# Set directory for folder
pre_fire_dir <- here::here("week6", "data", "LC80340322016189-SC20170128091153")

# Create a list of all images that have the extension .tif and contain the word band
pre_fire_bands <- list.files(pre_fire_dir,
                             pattern = glob2rx("*band*.tif$"),
                             full.names = TRUE)
# Create a raster stack
pre_fire_rast <- rast(pre_fire_bands)

# Read mask raster
pre_mask <- rast(here::here("week6", "data", "LC80340322016189-SC20170128091153", "LC80340322016189LGN00_cfmask_crop.tif"))
```


```{r}
# Set directory for folder
post_fire_dir <- here::here("week6","data", "LC80340322016205-SC20170127160728")

# Create a list of all images that have the extension .tif and contain the word band
post_fire_bands <- list.files(post_fire_dir,
                             pattern = glob2rx("*band*.tif$"),
                             full.names = TRUE)
# Create a raster stack
post_fire_rast <- rast(post_fire_bands)

# Read mask raster
post_mask <- rast(here::here("week6", "data", "LC80340322016205-SC20170127160728", "LC80340322016205LGN00_cfmask_crop.tif"))

```


```{r}
nbr_fun <- function(nir, swir2){
    (nir - swir2)/(nir + swir2)
}
```


```{r}
bands <- c("aerosol", "blue", "green", "red", "nir", "swir1", "swir2")

names(pre_fire_bands) <- bands

names(post_fire_bands) <- bands

```

```{r}
names(pre_fire_bands)
```

```{r}
pre_mask[pre_mask > 0] <- NA

post_mask[post_mask > 0] <- NA

pre_fire_rast <- mask(pre_fire_rast, mask = pre_mask)

# Subset raster based on mask
post_fire_rast <- mask(post_fire_rast, mask = post_mask)
```

```{r}
map1 <- tm_shape(pre_fire_rast) +
  tm_rgb(col = tm_vars(c(4,3,2), multivariate = TRUE))
map1
```
```{r}
map2 <- tm_shape(post_fire_rast) +
  tm_rgb(col = tm_vars(c(4,3,2), multivariate = TRUE))
map2
```

```{r}
plotRGB(pre_fire_rast, r = 4, g = 3, b = 2, stretch = "lin", colNA = "black")
```

```{r}
plotRGB(post_fire_rast, r = 4, g = 3, b = 2, stretch = "lin", colNA = "black")
```

```{r}
plotRGB(pre_fire_rast, r = 7, g = 5, b = 3, stretch = "lin", colNA = "black")
```

```{r}
plotRGB(post_fire_rast, r = 7, g = 5, b = 3, stretch = "lin", colNA = "black")
```

```{r}
nbr_rast_pre <- lapp(pre_fire_rast[[c(5, 7)]], fun = nbr_fun)

nbr_rast_post <- lapp(post_fire_rast[[c(5, 7)]], fun = nbr_fun)
```

```{r}
plot(nbr_rast_pre, main = "Cold Springs Pre-Fire NBR", colNA = "black")

```
```{r}
plot(nbr_rast_post, main = "Cold Springs Pre-Fire NBR", colNA = "black")
```
```{r}
dnbr <- nbr_rast_pre - nbr_rast_post
```

```{r}
tm_shape(dnbr) +
  tm_raster() +
  tm_layout(legend.outside = TRUE)
```


