---
title: "week2-discussion"
format: html
---

```{r}
library(tidyverse)
library(sf)
library(tmap)
```

```{r}
col <- st_read(here::here("week2", "data", "Colombia", "Colombia.shp"))

roads <- st_read(here::here("week2", "data", "RDLINE_colombia", "RDLINE_colombia.shp"))

aves <- read_csv(here::here("week2", "data", "dataves.csv")) %>%  
  as_tibble()  %>%  
  rename(long = decimal_longitude,
         lat = decimal_latitude) %>%  
  st_as_sf(coords = c("long", "lat"), crs = 4326)

```

```{r}
class(col)
class(roads)
class(aves)
```

```{r}
unique(st_geometry_type(col))
unique(st_geometry_type(roads))
unique(st_geometry_type(aves))
```
```{r}
col_caribbeo <- col %>% 
  filter(N1_MacroBi == "Caribbeo Mesoamerican")
```

```{r}
tm_shape(col_caribbeo) +
  tm_polygons()
```



```{r}
# View CRS of each object
st_crs(col)
st_crs(roads)
st_crs(aves)

# View units of each object CRS 
st_crs(col)$units
st_crs(roads)$units
st_crs(aves)$units
```


```{r}
aves_df_st_coords <- aves %>%
  dplyr::mutate(lon = st_coordinates(.)[,1], # Assign first matrix item to "lon"
                lat = st_coordinates(.)[,2])  %>% # Assign second matrix item to "lat"
  st_drop_geometry() # Remove geometry column now that it's redundant
```

```{r}
aves_df_purrr <- aves %>% 
  st_as_sf(coords = c("lon", "lat"), crs = 4326)
```

```{r}
# Boolen check if CRS match between 2 datasets
st_crs(col) == st_crs(roads)
```

```{r}
# Transform bird observation dataset into same CRS as other Colombia dataset
aves <- st_transform(aves, crs = st_crs(col))
```

```{r}
tm_shape(col) +
  tm_polygons() +
  tm_shape(roads) +
  tm_lines() +
  tm_shape(aves) +
  tm_dots() +
  tm_title("Colombia ecoregions, roads,\nand bird observations")

```



